name: Tests

on: [pull_request, push]

jobs:
  build:
    name: Tests - linux

    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build the docker image
        run: docker build -t testenv -f linux_test.dockerfile .

      - name: Run the image
        run: docker run devenv
  
  build:
    name: Tests - windows

    runs-on: windows

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build the docker image
        run: docker build -t testenv -f windows_test.dockerfile . 

      - name: Run the image
        run: docker run devenv
